os: osx
osx_image: xcode11
before_install:
- sudo systemsetup -settimezone Asia/Tokyo
script:
- export/add-keychain.sh
- make archive
branches:
  only:
  - master
  - "/^\\d+\\.\\d+(\\.\\d+)?$/"
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
  - ZIP_PATH=OctotreeForSafari-$TRAVIS_TAG.zip
  - secure: HzmvvSQk7/I93PA0oQDcreIGFMEcpr/fIfiUOlUf8oJ/jEk6wqSqoZN+ZXI97dQFXAtHsDcKMCKEZq1CCNiRo7kykpyH+NItK3vXCVEA5yp/6kM4wjAy+BI3XrN55xWKVpwwIC/a7mgjBU1PAf7zbAb1qKNAdjRhg3rQ0ctqbQYFuqx5yb9n6cpomlIP1SFJVnbLuH2sAVqkZWSSqn7kcIAnzD4TOFTbJXorotpM1AU/P2zHPPzxrJSPF36T4WROc2fHZv8eFIUwNnIY7tu0B6wsa/rLHINZvXZDAd8IpxUBbTl64NYjWm6xs6fjFcGMdjvxdLvI4CkjwZqfLdIoM9g/g/dhTSmSy9Bh0wKDAlChZuQtNm9ilKRTM+0NyV4qB/E8G8Y/PZgJg/uz7YId1XeNCCJXaozA0NgeCJ0DVind+SDwQ3ILrQuBPADPlleieSx7BTvX13k15v/fk2uBhP+Y1w2ZpBXyBt7xj9NYkEJ78FSBr22lZfkCOh9gleytzn3F4q6kAEPwhw4uVJZsYLdnvvzGnif0oKk/LRaP00ERBOjXR04bRzGJhWfTjtOj7WB9AjqdGZBJ1aQaTqcPuWqcaZDiUpyeDxmGTGY21VlPgX+nLei6dz0UY7HpU6VxdgN3loOko6XL4i8V+NOh7k7aQZmHDwx2pucrm6kHIR4=
  - secure: nrTEHcZpzGnjGP44Dpq1W66o0F+na8ZB53j6HfeM2wh4XyXWlhcMhtgzV1SAlUeE94rPjSz7hZAoCZY+ZzLHokJBVfjvdoSxL0l/d7ljpNy8GOjTWUtAgst0SY1DGQX5I7BNAj/d3nsllGIUGfF2bvfEN5UJaPC8BHAuNX+UFS/dLRsFrpzr6gyl393cbPl7wfsxKBoqGDBoQZbOpGczn65+wXfIBlTIKNVdjhX2/X/ewG9esSWw8IkB9oc3SwFN85+9V35ebXN96jkNz+MCI5t1Pe7Tr3egSjg15D/rJ2X+U/ZRcrSIUUkQuqg8GW6BJUSakT8N7Ygq+fHE801mjh0N1q33mjl1/P+9s7NTQX4wFcXR4FKygBX5A5+eREogIlRaphRtVXDBGcgELnnsMRe3Dc0/neh5Nxpsduw2oOFfAkAcziL3Co2Mdz+aj5O2TiiYbC90IvwymO/p2mxhpfnJxtDF2EUFVsH1b5cH9c9pzeruWj9/Ww0KrsT/o5Ncb49ruGtp8AtWK09ApziP+Ow7FZaUIa9GNkpmIPxkLet30zcE7U3lIIz7e74TW5jAg55Qb4rdcf9+xCCO9y2SGqT/PNiBp3//rLh7l7d0E/6IXT4t4dURpWDUu5KAgKliO7rGn77nI69mm5a2aXJbORI7sg2aYdEMAPqxlSgijII=
  - secure: jXMMd0+LAxn9lU1sT3nu22ZBY4/w+JiuuEK/8T/JD0K2uWNWZNGql8cxrnl0LRL3SioWo2lqAW6kohXi9XFCPY7kWwp3/gv9S3d/CvXuHjt+Eh06XNHFSsJKqu2+ucTHh8Y9a9KzvFDYWbb2Ui09fwoC1wLCf1QPFK1A6GMBBx6L1uAVzcPrxS3pakha9jwkpoQH6UVUcGYP3pkdWhsA/tTnhuIZ3DbND69rGvVhDjTbBUeGO9UJhrFPrn8YUyhYb4P0u4JoCZpH9xemTF4bqlHjV4YNiV7KfkBRNzLM6KCjePVgVwWponQPN5HWVAnHNwJXmLZUSWvu0xzmaZEcqEDJz6MfbEPOIj+pOxa5uQMuF8nLuQ9g7xPo/MArzpdzry3BlxEI8QCpNTF3xEh2XZpatBdMN9qjDWSU9awPg/614u4V1amLQJxdEdRYiSaACG5v1qfA1epQhT0vBImmrpl75f5yJgutFnrYe2vywTDNT5s2hEyO8XXq2Lm2Bf289ePbVGpgU0/3Yih9dqqYFPzkySvK7mTZ9gOiTfcwFbQtBxq7rSC8nn7DV+C4fhi0kGOBgBgu77A0GPh+hPFL3B/OUCxhz+ud30DcpcTAaDzCqAaqeRooKsZt0QoaZFjXhbvtq2DRrvRVtlcLKubSD4GnKm0LMHjxxSiD2z0eBdQ=
before_deploy:
- mkdir -p ~/.appstoreconnect/private_keys
- openssl aes-256-cbc -K $encrypted_3de8d6da74a4_key -iv $encrypted_3de8d6da74a4_iv
  -in private_keys/AuthKey.p8.enc -out ~/.appstoreconnect/private_keys/AuthKey_$API_KEY.p8
  -d
- make notarize
- rm -f ~/.appstoreconnect/private_keys/AuthKey_$API_KEY.p8
deploy:
  provider: releases
  api_key:
    secure: OmP/Sr5s/Cm8joQl1cyMcoCAvUB0s01AXSR4RXnvFICXchctaVlqtYvbOF80qAZVbw+1keF1PqPnfY2icohCXsWt242aW9nVO1Yelcr+2AFcuSd1f2vrnG+xzpDhwDbCkuXqsN8QtQSFL10kaJAf0SGJHrf7g5XBLWDV6ohV2nYVk7yn0v+UGIHu2zFgL8iMoiVO/iRQwrwou9Jz31AEL6cryrbEHOZkQ5UjosW8fdqSrI0nYkBYPzeY/TawhGuMNxMU+iac1Q442ji97eItmgE2zpkNXHsvwCejjfSQz/vmehRlZ7KjmD7e+TeKCg9/JzWlfcmC6Sp4Eo3JKusCDXZQ4ANSb31iYgncoabKMkmxleH57ULkI8vZkw6J9n32nYWHiaNvRG1lv6fob2hoCy+8kfIoptsMVoh9i8zTPTNzmqDyWtHNGb95o/4hW6q52VZy6tMtVf+8AazCmJ1x3Pv4zY/mkp7Pas/84tFFL/hKkvhbaYZ3vTyRRgO13eH+mCnOGOrBG3W1i0EEclBSTmMeEtrz4oBsNnAClDrswnks+0aRqoU+O+Le61BqfcXdjKN2y6Dvx4JyduFX5cbSUIg/XMiW+zD62Os0XfGb3a88VFLsOhJR92W57Nc2pZcoLqmhGrQi2Xb8OVfo+6e/t/yn0aPQuHqN+g3W5Hg0IaU=
  file: "$ZIP_PATH"
  on:
    tags: true
  skip_cleanup: true
after_deploy:
- export/remove-keychain.sh
